services:
  db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin

  app:
    build: ./
    ports:
      - 8000:8000
    volumes:
      - .env:/secrets/.env:ro
    # environment:
      # - INSTANCE_HOST=db
      # - DB_USER=postgres
      # - DB_PASS=admin
      # - DB_NAME=postgres
      # - DB_PORT=5432
