name: Build and Push to Artifact Registry

on:
  push:
    branches: ["master"]
  workflow_dispatch:


env:
  PROJECT_ID: oidc-project-1273
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/oidc-project-1273/app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: Git Info
        id: git_info
        run: |
          PREFIX=$(echo ${GITHUB_REF#refs/heads/} | tr [:upper:] [:lower:] | sed "s#[/_]#-#g")
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          echo "new tag: ${PREFIX}-${GITHUB_SHA::8}-b${TIMESTAMP}"
          echo "IMAGE_TAG=${PREFIX}-${GITHUB_SHA::8}-b${TIMESTAMP}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${PREFIX}" >> $GITHUB_ENV

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: |-
          docker build . --tag ${{ env.GAR_LOCATION }}/vote:$IMAGE_TAG

      - name: Push image
        run: |-
          docker push ${{ env.GAR_LOCATION }}/vote:$IMAGE_TAG
